export const CHANGE_PROFILE_NAME = "CHANGE_PROFILE_NAME";
export const CHANGE_PROFILE_EMAIL = "CHANGE_PROFILE_EMAIL";
export const CHANGE_PROFILE_PASSWORD = "CHANGE_PROFILE_PASSWORD";
export const TOGGLE_PROFILE_VISIBILITY_PASSWORD = 'TOGGLE_PROFILE_VISIBILITY_PASSWORD'
export const TOGGLE_PROFILE_NAME_FOCUS = 'TOGGLE_PROFILE_NAME_FOCUS'