export const CHANGE_REGISTER_NAME = "CHANGE_REGISTER_NAME";
export const CHANGE_REGISTER_EMAIL = "CHANGE_REGISTER_EMAIL";
export const CHANGE_REGISTER_PASSWORD = "CHANGE_REGISTER_PASSWORD";
export const TOGGLE_REGISTER_VISIBILITY_PASSWORD = 'TOGGLE_REGISTER_VISIBILITY_PASSWORD'