//burger constructor
export const SET_BUN: "SET_BUN" = "SET_BUN";
export const INIT_CONSTRUCTOR: "INIT_CONSTRUCTOR" = "INIT_CONSTRUCTOR";
export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const MOVE: "MOVE" = 'MOVE';


//burger-ingredients
export const CLICK_INGREDIENT: "CLICK_INGREDIENT" = "CLICK_INGREDIENT";
export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = 'GET_INGREDIENTS_FAILED';
export const SWITCH_TAB: "SWITCH_TAB" = 'SWITCH_TAB';

//forgot password
export const CHANGE_FORGOT_EMAIL: "CHANGE_FORGOT_EMAIL" = "CHANGE_FORGOT_EMAIL";

//login
export const CHANGE_LOGIN_EMAIL: "CHANGE_LOGIN_EMAIL" = "CHANGE_LOGIN_EMAIL";
export const CHANGE_LOGIN_PASSWORD: "CHANGE_LOGIN_PASSWORD" = "CHANGE_LOGIN_PASSWORD";
export const TOGGLE_LOGIN_VISIBILITY_PASSWORD: "TOGGLE_LOGIN_VISIBILITY_PASSWORD" = "TOGGLE_LOGIN_VISIBILITY_PASSWORD"

//modal
export const CLOSE_MODAL: "CLOSE_MODAL" = 'CLOSE_MODAL';

//order feed
export const WS_ORDER_FEED_CONNECT: "WS_ORDER_FEED_CONNECT" = "WS_ORDER_FEED_CONNECT";
export const WS_ORDER_FEED_DISCONNECT: "WS_ORDER_FEED_DISCONNECT" = "WS_ORDER_FEED_DISCONNECT";
export const WS_ORDER_FEED_CONNECTING: "WS_ORDER_FEED_CONNECTING" = "WS_ORDER_FEED_CONNECTING";
export const WS_ORDER_FEED_OPEN: "WS_ORDER_FEED_OPEN" =  "WS_ORDER_FEED_OPEN";
export const WS_ORDER_FEED_CLOSE: "WS_ORDER_FEED_CLOSE" = "WS_ORDER_FEED_CLOSE";
export const WS_ORDER_FEED_ERROR: "WS_ORDER_FEED_ERROR" = "WS_ORDER_FEED_ERROR";
export const WS_ORDER_FEED_MESSAGE: "WS_ORDER_FEED_MESSAGE" = "WS_ORDER_FEED_MESSAGE";

//order
export const POST_ORDER_REQUEST: "POST_ORDER_REQUEST" = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS" = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILED: "POST_ORDER_FAILED" = 'POST_ORDER_FAILED';

//profile feed
export const WS_PROFILE_FEED_CONNECT: "WS_PROFILE_FEED_CONNECT" = "WS_PROFILE_FEED_CONNECT";
export const WS_PROFILE_FEED_DISCONNECT: "WS_PROFILE_FEED_DISCONNECT" = "WS_PROFILE_FEED_DISCONNECT";
export const WS_PROFILE_FEED_CONNECTING: "WS_PROFILE_FEED_CONNECTING" = "WS_PROFILE_FEED_CONNECTING";
export const WS_PROFILE_FEED_OPEN: "WS_PROFILE_FEED_OPEN" =  "WS_PROFILE_FEED_OPEN";
export const WS_PROFILE_FEED_CLOSE: "WS_PROFILE_FEED_CLOSE" = "WS_PROFILE_FEED_CLOSE";
export const WS_PROFILE_FEED_ERROR: "WS_PROFILE_FEED_ERROR" = "WS_PROFILE_FEED_ERROR";
export const WS_PROFILE_FEED_MESSAGE: "WS_PROFILE_FEED_MESSAGE" = "WS_PROFILE_FEED_MESSAGE";

//profile
export const CHANGE_PROFILE_NAME: "CHANGE_PROFILE_NAME" = "CHANGE_PROFILE_NAME";
export const CHANGE_PROFILE_EMAIL: "CHANGE_PROFILE_EMAIL" = "CHANGE_PROFILE_EMAIL";
export const CHANGE_PROFILE_PASSWORD: "CHANGE_PROFILE_PASSWORD" = "CHANGE_PROFILE_PASSWORD";
export const TOGGLE_PROFILE_VISIBILITY_PASSWORD: "TOGGLE_PROFILE_VISIBILITY_PASSWORD" = 'TOGGLE_PROFILE_VISIBILITY_PASSWORD'
export const TOGGLE_PROFILE_NAME_FOCUS: "TOGGLE_PROFILE_NAME_FOCUS" = 'TOGGLE_PROFILE_NAME_FOCUS'

//register
export const CHANGE_REGISTER_NAME: "CHANGE_REGISTER_NAME" = "CHANGE_REGISTER_NAME";
export const CHANGE_REGISTER_EMAIL: "CHANGE_REGISTER_EMAIL" = "CHANGE_REGISTER_EMAIL";
export const CHANGE_REGISTER_PASSWORD: "CHANGE_REGISTER_PASSWORD" = "CHANGE_REGISTER_PASSWORD";
export const TOGGLE_REGISTER_VISIBILITY_PASSWORD: "TOGGLE_REGISTER_VISIBILITY_PASSWORD" = 'TOGGLE_REGISTER_VISIBILITY_PASSWORD'

//reset password

export const CHANGE_RESET_PASSWORD: "CHANGE_RESET_PASSWORD" = "CHANGE_RESET_PASSWORD";
export const CHANGE_RESET_CODE: "CHANGE_RESET_CODE" = "CHANGE_RESET_CODE";
export const TOGGLE_RESET_VISIBILITY: "TOGGLE_RESET_VISIBILITY" = "TOGGLE_RESET_VISIBILITY";

//user

export const POST_AUTH: 'POST_AUTH' = 'POST_AUTH';
export const POST_AUTH_SUCCESS: 'POST_AUTH_SUCCESS' = 'POST_AUTH_SUCCESS';
export const POST_AUTH_FAILED: 'POST_AUTH_FAILED' = 'POST_AUTH_FAILED';
export const POST_LOGOUT_USER: 'POST_LOGOUT_USER' = 'POST_LOGOUT_USER';
export const CHANGE_USER: 'CHANGE_USER' = 'CHANGE_USER';